### ISSUE TITLE
Status of the project?

### ISSUE THREAD

**Issue by dvtomas** [fsist/safepickle#11]
Hi,
I'm currently evaluating several pickling solutions, and I wonder, what is the current status of the project? There hasn't been a commit for over a year, is the project in active use? Does it work with latest Scala versions? If you were to choose a pickling solution today, would you still pick safepickle, or would you perhaps grab another solution that may have emerged meanwhile?

All in all, safepickle looks really nice. I need simple and safe solution, and like the ability to gradually version or completely override pickling implementation. 

Thank you, cheers,
  Tomas

**Comment by danarmak** [comment]
Hi Tomas,

I'm afraid the project is abandoned. The startup that I worked at which I needed this for has closed down, and I'm not using the library otherwise. I wouldn't recommend using it unless you're willing to take over as maintainer and build from there. I'll update the README to say as much.

As for alternatives, the two that come to mind are scala-pickling - whose main shortcoming IMO is that it's too complex and general - and uPickle, which is sort of the other way around, very stripped-down. It all depends on what you need. Having to write safepickle taught me there's no "right way to do it" in serialization semantics.

Both of these libraries are pickler combinators, so you can gradually override picklers for specific types. Neither has versioning semantics (that I know of), but I suppose they can be implemented on top.

Thanks for asking!

**Comment by dvtomas** [comment]
OK, thank you very much for the reply. I totally agree that scala-pickling is too complex. I do like uPickle, but the macro magic is sometimes unreliable - I've witnessed compiler hangs and other mysterious compilation errors.

I'll stick with json4s built-in serialization until I find something better. Thanks once again.

**Comment by danarmak** [comment]
safepickle also relies on macro magic, which I agree is hell to debug, and is also firmly deprecated.

I wouldn't use json4s though. It doesn't really know about scala types, because it uses Java reflection. As a result it doesn't support various Scala constructs the way you'd expect. Personally I'd rather deal with scala-pickling...
